### ISSUE TITLE
神人啊！

### ISSUE THREAD

**Issue by kitgary** [stanzhai/be-a-professional-programmer#14]
大神！你好厲害啊！想問你怎麼有這麼多時間去學這麼多技術？我也正在自學，還只是學些很低端的技術，不知何時才有你的水平。

**Comment by rogelx** [comment]
ddfdd

**Comment by stanzhai** [comment]
我不是什么神人，和牛人还有不少差距。保持兴趣，坚持动手去做，你也可以。
