### ISSUE TITLE
[need english]

### ISSUE THREAD

**Issue by ctrlaltvikas** [stanzhai/be-a-professional-programmer#7]
An english translation will also be much appreciated.

**Comment by newhope** [comment]
No, It's on purpose.

You need to know Chinese first to become a professional programmer  ¯\\\_ツ\_/¯

**Comment by ctrlaltvikas** [comment]
haha. I am on Jackie chan movies'. :rofl:

**Comment by anjia0532** [comment]
@newhope 这B装的我给满分，哈哈哈哈哈哈哈哈哈
